[build.environment]
  NPM_FLAGS = "--version"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "20"

[build]
  publish = "docs/.vitepress/dist"
  command = "yarn && yarn docs:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
